# Q1. 여러분은 파이썬을 통해 설문조사 문항의 응답내역을 분석하게 되었습니다. 문항별 응답내용에는 하나의 응답만 할 수 있는 single choice 문제와 여러 응답을 선택할 수 있는 multiple choice 문제가 있습니다. 2개를 구분하기 위해 single choice 문항 번호에 "_"를 표기하지 않기로 했습니다.

문항별 응답내역이 'question'에 담겨 있을 때, 조건문과 반복문을 사용하여 아래와 같은 결과가 출력되도록 코드를 작성해보세요.

In [ ]:
# 응답 설문 문항
question = ['Q2', 'Q3', 'Q4', 'Q5', 'Q6_1', 'Q6_2', 'Q6_3', 'Q6_4', 'Q6_5', 'Q6_6',
       'Q6_7', 'Q6_8', 'Q6_9', 'Q6_10', 'Q6_11', 'Q6_12', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q8', 'Q9', 'Q10_1', 'Q10_2',
       'Q10_3']

In [ ]:
result = [ i for i in question if '_' not in i]

In [ ]:
result

['Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q9']

# Q2. 다음의 데이터는 연도, 국가별 기대수명을 나타내고 있는 데이터 입니다. 2011년 부터의 연도별, 국가별 평균 기대수명을 구해주세요.(2011년도 포함되게 구합니다.)

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/healthexp.csv")
df

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [ ]:
df[df['Year']>=2011].groupby(['Year', 'Country'])['Life_Expectancy'].mean().unstack()

Country  Canada  France  Germany  Great Britain  Japan   USA
Year
2011       81.4    82.3     80.5           81.0   82.7  78.7
2012       81.6    82.1     80.6           81.0   83.2  78.8
2013       81.7    82.3     80.6           81.1   83.4  78.8
2014       81.8    82.8     81.2           81.4   83.7  78.9
2015       81.9    82.4     80.7           81.0   83.9  78.7
2016       82.0    82.7     81.0           81.2   84.1  78.7
2017       81.9    82.7     81.1           81.3   84.2  78.6
2018       82.0    82.8     81.0           81.3   84.3  78.7
2019       82.2    82.9     81.3           81.4   84.4  78.8
2020       81.7    82.3     81.1           80.4   84.7  77.0

# Q3. Jupyter notebook 은 문서와 코드를 함께 작성할 수 있다는 점이 장점입니다. Jupyter notebook 에서 지원하는 Markdown 문법을 사용하여, 이번 주에 배운 내용을 정리해 보세요!

- **Pandas 불러오기**

    ```python
    import python as pd
    ```

- **DataFrame**

    ```python
    df = pd.DataFrame(
    {"a" : [4, 5, 6],
    "b" : [7, 8, 9],
    "c" : [10, 11, 12]},
    index = [1, 2, 3])
    df
    ```

- **Series**

    ```python
    df["a"]
    ```

- **Subset (일부 값만 불러오기)**

    ```python
    # Rows 기준
    df[df.Length > 7]

    # Columns 기준
    df[['width', 'length', 'species']]
    ```

- **Summarize Data**

    ```python
    df["a"].value_counts()
    ```

- **Reshaping**

    ```python
    df["a"].sort_values()  # 오름차순
    df["a"].sort_values(ascending=False)  # 내림차순
    
    df.drop(["c"], axis=1)  # 'c' 컬럼 drop
    ```

- **Group Data**

    ```python
    df.groupby(["a"])["b"].mean()
    
    pd.pivot_table(df, index="a")
    ```

- **Plotting**

    ```python
    df.plot()  # 꺾은선 그래프
    df.plot.bar()  # 막대 그래프
    df.plot.density()  #  밀도 함수 그래프
    ```

# Q4. 공공데이터포털에서 원하는 데이터를 다운로드 받아 경로를 설정하고, 주피터 노트북과 판다스를 통해 불러와 보세요!

In [ ]:
df = pd.read_csv('서울특별시 강남구_생활폐기물배출량_20221019.csv', encoding='cp949')

FileNotFoundError: ignored

In [ ]:
df